### ISSUE TITLE
[BUG] bytes no longer supported

### ISSUE THREAD

**Issue by TinyTheBrontosaurus** [MORSECorp/snappiershot#81]
**Describe the bug**
`bytes` was serialized as integers in `v0.2.0`. Now in `v1.0.0` they're no longer supported

**To Reproduce**

The test:
```
def test_bytes(snapshot):
    snapshot.assert_match(b"hello world")
```

Result in `v1.0.0`:

```
Traceback (most recent call last):
  File "/home/ttb/ttb/test/test_tag_usb.py", line 145, in <module>
    test_bytes(s)
  File "/home/ttb/.venv/lib/python3.7/site-packages/snappiershot/snapshot/snapshot.py", line 148, in __exit__
    self._snapshot_file.write()
  File "/home/ttb/.venv/lib/python3.7/site-packages/snappiershot/snapshot/_file.py", line 142, in write
    indent=self.config.json_indentation,
  File "/home/ttb/.venv/lib/python3.7/site-packages/snappiershot/serializers/io.py", line 50, in write_json_file
    json.dump(obj, snapshot_file, cls=JsonSerializer, indent=indent, sort_keys=True)
  File "/home/ttb/.pyenv/versions/3.7.3/lib/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/home/ttb/.pyenv/versions/3.7.3/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/home/ttb/.pyenv/versions/3.7.3/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/ttb/.pyenv/versions/3.7.3/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/ttb/.pyenv/versions/3.7.3/lib/python3.7/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/home/ttb/.pyenv/versions/3.7.3/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/ttb/.pyenv/versions/3.7.3/lib/python3.7/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/home/ttb/.pyenv/versions/3.7.3/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/ttb/.venv/lib/python3.7/site-packages/snappiershot/serializers/json.py", line 80, in default
    f"Encoding for this object is not yet implemented: {value} ({type(value)})"
NotImplementedError: Encoding for this object is not yet implemented: b'hello world' (<class 'bytes'>)
```

Result in `v0.2.0`:
```
    "snappiershot_version": "0.2.0",
    "tests": {
        "test_bytes": [
            {
                "metadata": {
                    "arguments": {},
                    "test_runner_provided_name": "",
                    "update_on_next_run": false,
                    "user_provided_name": ""
                },
                "snapshots": [
                    [
                        104,
                        101,
                        108,
                        108,
                        111,
                        32,
                        119,
                        111,
                        114,
                        108,
                        100
                    ]
                ]
            }
        ],
```

But worth noting that the snapshot does fail if an update is not forced:
```
Traceback (most recent call last):
  File "/home/ttb/ttb/test/test_tag_usb.py", line 145, in <module>
    test_bytes(s)
  File "/home/ttb/ttb/test/test_tag_usb.py", line 142, in test_bytes
    snapshot.assert_match(b"hello world")
  File "/home/ttb/.venv/lib/python3.7/site-packages/snappiershot/snapshot/snapshot.py", line 90, in assert_match
    raise AssertionError(message)
AssertionError: Snapshot does not match:
- b'hello world'
+ [104, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100]
------------------------------------------------------------------------------
Summary:
  > Types not equal: <class 'bytes'> != <class 'list'>
```
**Expected behavior**
`bytes` to be written to the snapshot

**Screenshots**

**Versions:**
 - Python version: 3.7.3 (pyenv)
 - Snappiershot version: `1.0.0` (catastrophic) and `0.2.0` (workable)

**Additional context**

**Comment by bbonenfant** [comment]
This appears to be due to a difference between how the `json.dump` and `json.dumps` functions work. This is a quirk that we were not aware of, but should be able to quickly fix.
